const { chromium, expect } = require('@playwright/test');
const assert = require('node:assert/strict');
const base = process.env.TEST_URL || 'http://127.0.0.1:5178';

(async () => {
  const browser = await chromium.launch({channel: process.env.TEST_BROWSER || 'chrome', headless: true, args: ['--enable-webgl', '--ignore-gpu-blocklist']});
  const page = await browser.newPage({viewport: {width: 1280, height: 900}, reducedMotion: 'reduce'});
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base);
  await page.waitForFunction(() => document.querySelector('.scene-host')?.dataset.mode === 'overview');
  const filters = page.locator('.discovery-filters');
  await filters.getByLabel('Stand', {exact: true}).selectOption('south');
  await page.waitForFunction(() => document.querySelector('.discovery-filters select[aria-label="Tier"] option[value="upper"]')?.disabled);
  assert.notEqual(await filters.getByLabel('Tier', {exact: true}).locator('option[value="upper"]').getAttribute('disabled'), null);
  await filters.getByLabel('Tier', {exact: true}).selectOption('terrace');
  await filters.getByLabel('Category', {exact: true}).selectOption('terrace');
  await filters.getByLabel('People', {exact: true}).selectOption('3');
  await filters.getByLabel('Max demo price / person', {exact: true}).selectOption('20');
  await page.waitForFunction(() => document.querySelector('.result-heading strong')?.textContent?.includes('matching places'));
  assert.ok(Number((await page.locator('.result-heading strong').textContent()).replace(/\D/g, '')) > 0);
  assert.ok((await page.locator('.mini-map').getAttribute('aria-label')).includes('Filtered to South stand'));
  assert.ok((await page.locator('.result-item').first().textContent()).includes('South stand'));
  await page.locator('.result-item').first().click();
  assert.match(await page.locator('.selected-details').textContent(), /Standing area · unassigned/);
  assert.match(await page.locator('.selected-details').textContent(), /People requested3/);
  await page.getByRole('button', {name: /Add to demo selection/}).click();
  assert.match(await page.locator('.demo-confirmation').textContent(), /3 people.*€60 demo total/);
  assert.match(await page.locator('.demo-confirmation').textContent(), /Nothing is reserved/);
  await page.getByRole('button', {name: 'Preview this view'}).click();
  await page.waitForFunction(() => document.querySelector('.scene-host')?.dataset.mode === 'preview');
  await filters.getByLabel('Category', {exact: true}).selectOption('sideline');
  await page.waitForFunction(() => document.querySelector('.scene-host')?.dataset.mode === 'overview');
  await expect(page.locator('.selected-details')).toHaveCount(0);
  assert.match(await page.locator('.results-empty').textContent(), /No places match/);
  assert.ok((await page.locator('.mini-map').getAttribute('aria-label')).includes('Filtered to South stand'));
  await page.getByRole('button', {name: 'Reset all filters'}).click();
  await filters.getByLabel('Stand', {exact: true}).selectOption('west');
  const unavailable = page.locator('.result-item').filter({hasText: 'Unavailable'}).first();
  await unavailable.click();
  assert.equal(await page.getByRole('button', {name: /Add to demo selection/}).isDisabled(), true);
  assert.match(await page.locator('.unavailable-note').textContent(), /unavailable in the demo/);
  await page.getByRole('button', {name: 'Show available alternative'}).click();
  assert.match(await page.locator('.selected-details').textContent(), /available/i);
  await filters.getByLabel('People', {exact: true}).selectOption('4');
  assert.ok(Number((await page.locator('.result-heading strong').textContent()).replace(/\D/g, '')) > 0);
  await page.locator('.result-item').first().click();
  await page.getByRole('button', {name: /Add to demo selection/}).click();
  assert.match(await page.locator('.demo-confirmation').textContent(), /4 people.*€248 demo total/);
  assert.match(await page.locator('.demo-confirmation').textContent(), /consecutive in one demo row/);
  await page.setViewportSize({width: 390, height: 844});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('PASS combined filters, standing quantity, demo selection, preview reset, empty state, unavailable alternative, mobile width');
})().catch(error => { console.error(error); process.exit(1); });
