const { chromium, expect } = require('@playwright/test');
const assert = require('node:assert/strict');
const base = process.env.TEST_URL || 'http://127.0.0.1:5178';

(async () => {
  const browser = await chromium.launch({channel: process.env.TEST_BROWSER || 'chrome', headless: true, args: ['--enable-webgl', '--ignore-gpu-blocklist']});
  const page = await browser.newPage({viewport: {width: 1280, height: 900}, reducedMotion: 'reduce'});
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base);
  await page.waitForFunction(() => document.querySelector('.scene-host')?.dataset.mode === 'overview');
  const panel = page.getByRole('complementary', {name: 'Place explorer'});
  const stage = number => expect(panel).toHaveAttribute('data-stage', String(number));
  const chooseStand = async name => {
    const change = page.getByRole('button', {name: 'Change stand', exact: true});
    if (await change.isVisible().catch(() => false)) await change.click();
    await page.locator('.stand-selector').getByRole('button', {name, exact: true}).click();
  };
  const preview = async () => {
    await page.getByRole('button', {name: 'Preview this view'}).click();
    await page.waitForFunction(() => document.querySelector('.scene-host')?.dataset.mode === 'preview');
    await stage(4);
  };
  await stage(1);
  await expect(page.locator('.discovery-filters')).toBeHidden();
  await expect(page.locator('.representative-views')).toHaveCount(0);
  await chooseStand('West stand');
  await stage(2);
  await expect(page.locator('.representative-views button')).toHaveCount(3);
  await expect(page.locator('.advanced-places')).not.toHaveAttribute('open', '');
  await expect(page.locator('.result-pages')).toBeHidden();
  await expect(page.locator('.place-fields')).toBeHidden();
  await page.getByRole('button', {name: /Middle view/}).click();
  await stage(3);
  const novicePlace = await page.locator('.place-id').textContent();
  await expect(page.locator('.selected-details')).not.toContainText('Demo price');
  await expect(page.locator('.discovery-filters')).toBeHidden();
  await preview();
  await page.locator('.scene-frame').press('Escape');
  await stage(3);
  await expect(page.getByRole('button', {name: 'Preview this view'})).toBeFocused();
  await page.getByRole('button', {name: 'Change place', exact: true}).click();
  await stage(2);
  await expect(page.getByRole('button', {name: /Middle view/})).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByRole('button', {name: /Middle view/})).toBeFocused();
  await page.getByRole('button', {name: /Middle view/}).click();
  await expect(page.locator('.place-id')).toHaveText(novicePlace);
  await page.getByRole('button', {name: 'Change stand', exact: true}).click();
  await stage(1);
  await chooseStand('South stand');
  await stage(2);
  await page.locator('.advanced-places summary').click();
  const filters = page.locator('.discovery-filters');
  await page.waitForFunction(() => document.querySelector('.discovery-filters select[aria-label="Tier"] option[value="upper"]')?.disabled);
  assert.notEqual(await filters.getByLabel('Tier', {exact: true}).locator('option[value="upper"]').getAttribute('disabled'), null);
  await filters.getByLabel('Tier', {exact: true}).selectOption('terrace');
  await filters.getByLabel('Category', {exact: true}).selectOption('terrace');
  await filters.getByLabel('People', {exact: true}).selectOption('3');
  await filters.getByLabel('Max demo price / person', {exact: true}).selectOption('20');
  await page.waitForFunction(() => document.querySelector('.result-heading strong')?.textContent?.includes('matching places'));
  assert.ok(Number((await page.locator('.result-heading strong').textContent()).replace(/\D/g, '')) > 0);
  assert.ok((await page.locator('.orientation .mini-map').getAttribute('aria-label')).includes('Filtered to South stand'));
  assert.ok((await page.locator('.result-item').first().textContent()).includes('South stand'));
  await page.locator('.advanced-places summary').click();
  await expect(filters).toBeHidden();
  await page.locator('.advanced-places summary').click();
  await expect(filters.getByLabel('People', {exact: true})).toHaveValue('3');
  await page.getByRole('button', {name: 'Next', exact: true}).click();
  const resultPage = await page.locator('.result-pages span').textContent();
  await page.locator('.result-item').first().click();
  await stage(3);
  assert.match(await page.locator('.selected-details').textContent(), /Standing area · unassigned/);
  assert.match(await page.locator('.selected-details').textContent(), /People requested3/);
  await preview();
  await expect(page.getByRole('button', {name: 'Preview this view'})).toHaveCount(0);
  await page.getByRole('button', {name: /Save viewpoint/}).click();
  await expect(page.getByRole('button', {name: 'Remove saved viewpoint'})).toHaveCount(1);
  assert.match(await page.locator('.saved-viewpoint-confirmation').textContent(), /3 people/);
  assert.match(await page.locator('.saved-viewpoint-confirmation').textContent(), /standing-area sample/);
  await page.getByRole('button', {name: 'Change place', exact: true}).click();
  await stage(2);
  await expect(page.locator('.advanced-places')).toHaveAttribute('open', '');
  await expect(page.locator('.result-pages span')).toHaveText(resultPage);
  await expect(filters.getByLabel('People', {exact: true})).toHaveValue('3');
  await filters.getByLabel('Category', {exact: true}).selectOption('sideline');
  await page.waitForFunction(() => document.querySelector('.scene-host')?.dataset.mode === 'overview');
  await expect(page.locator('.selected-details')).toHaveCount(0);
  assert.match(await page.locator('.results-empty').textContent(), /No places match/);
  await expect(page.locator('.discovery-notice')).toContainText('no longer matches');
  assert.ok((await page.locator('.orientation .mini-map').getAttribute('aria-label')).includes('Filtered to South stand'));
  await page.getByRole('button', {name: 'Reset filters'}).click();
  await filters.getByLabel('Stand', {exact: true}).selectOption('west');
  const unavailable = page.locator('.result-item').filter({hasText: 'Unavailable'}).first();
  await unavailable.click();
  await preview();
  assert.equal(await page.getByRole('button', {name: /Save viewpoint/}).isDisabled(), true);
  assert.match(await page.locator('.unavailable-note').textContent(), /unavailable in the demo/);
  await page.getByRole('button', {name: 'Show available alternative'}).click();
  await stage(3);
  assert.match(await page.locator('.selected-details').textContent(), /available/i);
  await page.getByRole('button', {name: 'Change place', exact: true}).click();
  await filters.getByLabel('People', {exact: true}).selectOption('4');
  assert.ok(Number((await page.locator('.result-heading strong').textContent()).replace(/\D/g, '')) > 0);
  await page.locator('.result-item').first().click();
  await preview();
  const savedId = await page.locator('.place-id').textContent();
  await page.getByRole('button', {name: /Save viewpoint/}).click();
  assert.match(await page.locator('.saved-viewpoint-confirmation').textContent(), /4 people/);
  assert.match(await page.locator('.saved-viewpoint-confirmation').textContent(), /viewing location in the model/);
  await page.getByRole('button', {name: 'Change place', exact: true}).click();
  await stage(2);
  await page.getByRole('combobox', {name: 'Demo block', exact: true}).selectOption('DEMO-WEST-04');
  await page.getByRole('combobox', {name: 'Tier in block', exact: true}).selectOption('DEMO-WEST-04-UPPER');
  await page.getByRole('combobox', {name: 'Row', exact: true}).selectOption('DEMO-WEST-04-UPPER-R11');
  const exactPlace = await page.getByRole('combobox', {name: 'Seat', exact: true}).inputValue();
  await page.getByRole('button', {name: 'Select this place'}).click();
  await stage(3);
  await expect(page.locator('.place-id')).toHaveText(exactPlace);
  await page.getByRole('button', {name: 'Change place', exact: true}).click();
  await expect(page.getByRole('combobox', {name: 'Seat', exact: true})).toHaveValue(exactPlace);
  await chooseStand('South stand');
  await expect(filters.getByLabel('Tier', {exact: true})).toHaveValue('all');
  await expect(filters.getByLabel('People', {exact: true})).toHaveValue('4');
  // The saved viewpoint is independent of the current selection: it can be reopened, then removed.
  await expect(page.locator('.saved-viewpoint-confirmation')).toContainText('Saved viewpoint');
  await page.getByRole('button', {name: 'View saved viewpoint'}).click();
  await stage(3);
  await expect(page.locator('.place-id')).toHaveText(savedId);
  await expect(page.locator('.saved-viewpoint-confirmation')).toContainText('Viewpoint saved');
  await page.getByRole('button', {name: 'Remove saved viewpoint'}).click();
  await expect(page.locator('.saved-viewpoint-confirmation')).toHaveCount(0);
  await expect(page.locator('.discovery-notice')).toContainText('Saved viewpoint removed');
  await page.getByRole('button', {name: 'Change place', exact: true}).click();
  await stage(2);
  await page.setViewportSize({width: 390, height: 844});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.locator('.advanced-places summary').click();
  await page.getByRole('button', {name: /Lower view/}).click();
  await preview();
  await page.locator('.scene-host canvas').evaluate(canvas => canvas.dispatchEvent(new Event('webglcontextlost', {cancelable: true})));
  await expect(page.getByRole('alert')).toContainText('3D graphics paused');
  await stage(3);
  await expect(page.getByRole('button', {name: 'Preview this view'})).toBeDisabled();
  await page.getByRole('button', {name: 'Change place', exact: true}).click();
  await page.getByRole('button', {name: /Upper view/}).click();
  await stage(3);
  await page.getByRole('button', {name: 'Retry 3D'}).click();
  await expect(page.getByRole('button', {name: 'Preview this view'})).toBeEnabled();
  await preview();
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('PASS four-stage novice flow, Back/Edit focus, Advanced persistence, filters, pagination, exact selectors, empty/unavailable states, demo action, mobile preview, WebGL recovery');
})().catch(error => { console.error(error); process.exit(1); });
